# Change these first
owner: 1337Nerd # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Authentik
    url: https://authentik.joshuastock.net
  - name: Dash
    url: https://dash.joshuastock.net
  - name: Filebrowser
    url: https://filebrowser.joshuastock.net
  - name: Grafana
    url: https://dashboard.joshuastock.net
  - name: Homarr
    url: https://homarr.joshuastock.net
  - name: Invoke AI
    url: https://invoke.joshuastock.net
  - name: Jellyfin
    url: https://jellyfin.joshuastock.net
  - name: Jellyseerr
    url: https://jellyseerr.joshuastock.net
  - name: jfa-go
    url: https://jfa-go.joshuastock.net
  - name: Ollama
    url: https://ollama.joshuastock.net
  - name: Portainer
    url: https://portainer.joshuastock.net
  - name: Portfolio
    url: https://joshuastock.net
  - name: Prowlarr
    url: https://prowlarr.joshuastock.net
  - name: Radarr
    url: https://radarr.joshuastock.net
  - name: Sonarr
    url: https://sonarr.joshuastock.net
  - name: Syncthing
    url: https://syncthing.joshuastock.net
  - name: Torrent
    url: https://torrent.joshuastock.net
  - name: Transmission
    url: https://transmission.joshuastock.net
  - name: Twitch
    url: https://twitch.joshuastock.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: upptime.joshuastock.net
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: night
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
