# Change these first
owner: 1337Nerd # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Authentik
    url: https://authentik.joshuastock.net
  - name: Dash
    url: https://dash.joshuastock.net
  - name: Filebrowser
    url: https://filebrowser.joshuastock.net
  - name: Grafana
    check: "tcp-ping"
    url: dashboard.joshuastock.net
    port: 443
  - name: Homarr
    url: https://homarr.joshuastock.net
  - name: Invoke AI
    url: https://invoke.joshuastock.net
  - name: Jellyfin
    url: https://jellyfin.joshuastock.net
  - name: Jellyseerr
    url: https://jellyseerr.joshuastock.net
  - name: jfa-go
    url: https://jfa-go.joshuastock.net
  - name: Ollama
    url: https://ollama.joshuastock.net
  - name: Portainer
    url: https://portainer.joshuastock.net
  - name: Portfolio
    url: https://joshuastock.net
  - name: Prowlarr
    url: https://prowlarr.joshuastock.net
  - name: Radarr
    url: https://radarr.joshuastock.net
  - name: Slskd
    url: https://slskd.joshuastock.net
  - name: Sonarr
    url: https://sonarr.joshuastock.net
  - name: Syncthing
    url: https://syncthing.joshuastock.net
  - name: Torrent
    url: https://torrent.joshuastock.net
  - name: Transmission
    url: https://transmission.joshuastock.net
  - name: Twitch
    url: https://twitch.joshuastock.net
  - name: Webtop
    url: https://arch.joshuastock.net
  - name: Webtop VPN
    url: https://vpn.joshuastock.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.joshuastock.net
  # baseUrl: /uptime
  logoUrl: https://gitlab.com/1337_Nerd/portfolio/-/raw/main/src/lib/assets/icon.svg
  theme: light
  name: Status
  robotsText: "User-agent: *\nDisallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
